title: <img src="https://raw.githubusercontent.com/Lunatoid/FEL/master/docs/FEL-badge-light.png" alt="Logo" width=520px />
description: An easy event-chaining scripting language made in C++
baseurl: "/FEL"
show_downloads: true
theme: jekyll-theme-cayman
