highlighter: rogue
theme: jekyll-theme-cayman
title: "FEL | Docs"
description: The documentation of Flag Event Language
name: <img src="https://raw.githubusercontent.com/Lunatoid/FEL/master/docs/FEL-badge-light.png" alt="Logo" width=520px />
